export const environment = {
  production: true,
  apiEndpoint: 'https://piyali-ecommerce.herokuapp.com/',
  API_CATEGORY_PATH: 'api/categories',
  API_CONTENT_PATH: 'api/content',
  API_PRODUCT_LIST_PATH: 'api/products',
  API_PRODUCT_DETAILS_PATH: 'api/products/productdetails',
  API_PRODUCT_ADD_PATH: '',
  API_PRODUCT_DELETE_PATH: '',
  API_REGISTER_PATH: 'api/auth/register',
  API_LOGIN_PATH: 'api/auth/login',
  API_CART_PATH: 'api/cart',
  API_CART_CHECK_PRODUCT: 'api/cart/check',
  API_CART_ADD_PRODUCT_QUANTITY: 'api/cart/addqty',
  API_CART_DELETE_PRODUCT_QUANTITY: 'api/cart/deleteqty',
  API_CART_REMOVE_PRODUCT: 'api/cart/removeprod',
  API_CUSTOMERSBYYEAR: 'api/admin/customersbyyear',
  API_CUTOMERSBYGENDER: 'api/admin/customersbygender',
  API_PRODUCTSBYCATEGORY: 'api/admin/productsbycategory',
  IMAGE_PATH: 'images/products/',
  ERROR_MSG_PATH: 'api/errors',
  VALIDATION_ERROR_MSG_PATH: 'api/validationerrors'
};
